// seed the database

import * as users from "../data/users.js";
import { dbConnection, closeConnection } from "../config/mongoConnection.js";

const u = [
  {
    name: "John Doe",
    email: "johndoe@example.com",
    password: "Password1234$",
    age: 25,
    gender: "male",
    zip: "10001",
    bio: "I love hiking and playing video games",
    preferences: ["hiking", "video games"],
    image_destination: "public/uploads/",
    image_filename: "1.jpg",
    image_path: "public/uploads/1.jpg",
    university: "Harvard University",
    work: "Software Engineer",
    gym: "Gold's Gym",
    bucketlist: ["skydiving", "traveling to Japan"],
  },
  {
    name: "Jane Smith",
    email: "janesmith@example.com",
    password: "Password1234$",
    age: 28,
    gender: "female",
    zip: "20002",
    bio: "I'm a foodie and I love trying new restaurants",
    preferences: ["food", "travel"],
    image_destination: "public/uploads/",
    image_filename: "2.jpg",
    image_path: "public/uploads/2.jpg",
    university: "Yale University",
    work: "Marketing Manager",
    gym: "SoulCycle",
    bucketlist: ["skydiving", "traveling to Europe"],
  },
  {
    name: "Mike Johnson",
    email: "mikejohnson@example.com",
    password: "Password1234$",
    age: 30,
    gender: "male",
    zip: "90001",
    bio: "I'm a musician and I love playing guitar",
    preferences: ["music", "travel"],
    image_destination: "public/uploads/",
    image_filename: "3.jpg",
    image_path: "public/uploads/3.jpg",
    university: "University of California, Los Angeles",
    work: "Musician",
    gym: "Equinox",
    bucketlist: ["skydiving", "traveling to Australia"],
  },
  {
    name: "Sarah Davis",
    email: "sarahdavis@example.com",
    password: "Password1234$",
    age: 26,
    gender: "female",
    zip: "10002",
    bio: "I love reading and going on hikes",
    preferences: ["reading", "hiking"],
    image_destination: "public/uploads/",
    image_filename: "4.jpg",
    image_path: "public/uploads/4.jpg",
    university: "Stanford University",
    work: "Journalist",
    gym: "24 Hour Fitness",
    bucketlist: ["skydiving", "traveling to Italy"],
  },
  {
    name: "David Jones",
    email: "davidjones@example.com",
    password: "Password1234$",
    age: 27,
    gender: "male",
    zip: "10003",
    bio: "I'm a fitness enthusiast and I love working out",
    preferences: ["fitness", "travel"],
    image_destination: "public/uploads/",
    image_filename: "5.webp",
    image_path: "public/uploads/5.webp",
    university: "Columbia University",
    work: "Personal Trainer",
    gym: "Crunch Fitness",
    bucketlist: ["running a marathon", "traveling to Africa"],
  },
  {
    name: "Emily Brown",
    email: "emilybrown@example.com",
    password: "Password1234$",
    age: 29,
    gender: "female",
    zip: "10004",
    bio: "I'm a fashion lover and I love trying new clothes",
    preferences: ["fashion", "travel"],
    image_destination: "public/uploads/",
    image_filename: "5.webp",
    image_path: "public/uploads/5.webp",
    university: "New York University",
    work: "Fashion Stylist",
    gym: "Pure Barre",
    bucketlist: ["opening my own fashion line", "traveling to Paris"],
  },
  // {
  //   name: "Peter Green",
  //   name: "petergreen@example.com",
  //   password: "Password1234$",
  //   age: 31,
  //   gender: "male",
  //   zip: "10005",
  //   bio: "I'm a techie and I love working on computers",
  //   preferences: ["tech", "travel"],
  //   image_destination: "public/uploads/",
  //   image_filename: "5.webp",
  //   image_path: "public/uploads/5.webp",
  //   university: "Stanford University",
  //   work: "Software Engineer",
  //   gym: "Googleplex Gym",
  //   bucketlist: ["building my own startup", "traveling to Silicon Valley"],
  // },
  {
    name: "Alice White",
    email: "alicewhite@example.com",
    password: "Password1234$",
    age: 24,
    gender: "female",
    zip: "10006",
    bio: "I'm a student and I love learning new things",
    preferences: ["learning", "travel"],
    image_destination: "public/uploads/",
    image_filename: "5.webp",
    image_path: "public/uploads/5.webp",
    university: "New York University",
    work: "Student",
    gym: "NYU Fitness Center",
    bucketlist: ["getting a PhD", "traveling to all 7 continents"],
  },
  {
    name: "Alexandra Miller",
    email: "alexandramiller@example.com",
    password: "Password1234$",
    age: 25,
    gender: "female",
    zip: "94102",
    bio: "I'm a writer and I love to read",
    preferences: ["writing", "reading"],
    image_destination: "public/uploads/",
    image_filename: "5.webp",
    image_path: "public/uploads/5.webp",
    university: "University of California, Berkeley",
    work: "Freelance Writer",
    gym: "Crunch Fitness",
    bucketlist: ["writing a novel", "traveling to all 50 states"],
  },
  {
    name: "Benjamin Smith",
    email: "benjaminsmith@example.com",
    password: "Password1234$",
    age: 28,
    gender: "male",
    zip: "94103",
    bio: "I'm a musician and I love to play the guitar",
    preferences: ["music", "playing guitar"],
    image_destination: "public/uploads/",
    image_filename: "5.webp",
    image_path: "public/uploads/5.webp",
    university: "San Francisco State University",
    work: "Musician",
    gym: "Equinox",
    bucketlist: ["playing in a band", "traveling to Europe"],
  },
  {
    name: "Caroline Jones",
    email: "carolinejones@example.com",
    password: "Password1234$",
    age: 30,
    gender: "female",
    zip: "94104",
    bio: "I'm a student and I love to learn new things",
    preferences: ["learning", "travel"],
    image_destination: "public/uploads/",
    image_filename: "5.webp",
    image_path: "public/uploads/5.webp",
    university: "University of California, San Francisco",
    work: "Student",
    gym: "24 Hour Fitness",
    bucketlist: ["getting a PhD", "traveling to all 7 continents"],
  },
  {
    name: "Daniel Thomas",
    email: "danielthomas@example.com",
    password: "Password1234$",
    age: 26,
    gender: "male",
    zip: "94105",
    bio: "I'm a fitness enthusiast and I love working out",
    preferences: ["fitness", "travel"],
    image_destination: "public/uploads/",
    image_filename: "5.webp",
    image_path: "public/uploads/5.webp",
    university: "Stanford University",
    work: "Personal Trainer",
    gym: "Crunch Fitness",
    bucketlist: ["running a marathon", "traveling to Africa"],
  }, {    name: "Jasmine Nguyen",    email: "jasminenguyen@example.com",    password: "Password1234$",    age: 28,    gender: "female",    zip: "10001",    bio: "I love hiking and playing video games",    preferences: ["hiking", "video games"],
  image_destination: "public/uploads/",
  image_filename: "5.webp",
  image_path: "public/uploads/",
  university: "Harvard University",
  work: "Software Engineer",
  gym: "Gold's Gym",
  bucketlist: ["skydiving", "traveling to Japan"],
},
{
  name: "Ethan Lee",
  email: "ethanlee@example.com",
  password: "Password1234$",
  age: 27,
  gender: "male",
  zip: "20002",
  bio: "I'm a foodie and I love trying new restaurants",
  preferences: ["food", "travel"],
  image_destination: "public/uploads/",
  image_filename: "5.webp",
  image_path: "public/uploads/",
  university: "Yale University",
  work: "Marketing Manager",
  gym: "SoulCycle",
  bucketlist: ["skydiving", "traveling to Europe"],
},
{
  name: "Ava Chen",
  email: "avachen@example.com",
  password: "Password1234$",
  age: 31,
  gender: "female",
  zip: "90001",
  bio: "I'm a musician and I love playing guitar",
  preferences: ["music", "travel"],
  image_destination: "public/uploads/",
  image_filename: "5.webp",
  image_path: "public/uploads/",
  university: "University of California, Los Angeles",
  work: "Musician",
  gym: "Equinox",
  bucketlist: ["skydiving", "traveling to Australia"],
},
{
  name: "Michael Johnson",
  email: "michaeljohnson@example.com",
  password: "Password1234$",
  age: 26,
  gender: "male",
  zip: "10002",
  bio: "I love reading and going on hikes",
  preferences: ["reading", "hiking"],
  image_destination: "public/uploads/",
  image_filename: "5.webp",
  image_path: "public/uploads/",
  university: "Stanford University",
  work: "Journalist",
  gym: "24 Hour Fitness",
  bucketlist: ["skydiving", "traveling to Italy"],
},
{
  name: "Olivia Davis",
  email: "oliviadavis@example.com",
  password: "Password1234$",
  age: 29,
  gender: "female",
  zip: "10003",
  bio: "I'm a fitness enthusiast and I love working out",
  preferences: ["fitness", "travel"],
  image_destination: "public/uploads/",
  image_filename: "5.webp",
  image_path: "public/uploads/",
  university: "Columbia University",
  work: "Personal Trainer",
  gym: "Crunch Fitness",
  bucketlist: ["running a marathon", "traveling to Africa"],
},{
  name: "Emma Garcia",
  email: "emmagarcia@example.com",
  password: "Password1234$",
  age: 32,
  gender: "female",
  zip: "90002",
  bio: "I'm a writer and I love going to the beach",
  preferences: ["reading", "beach"],
  image_destination: "public/uploads/",
  image_filename: "5.webp",
  image_path: "public/uploads/",
  university: "New York University",
  work: "Writer",
  gym: "LA Fitness",
  bucketlist: ["traveling to Hawaii", "learning to surf"],
},
{
  name: "William Baker",
  email: "williambaker@example.com",
  password: "Password1234$",
  age: 28,
  gender: "male",
  zip: "20003",
  bio: "I'm a photographer and I love taking pictures of nature",
  preferences: ["photography", "hiking"],
  image_destination: "public/uploads/",
  image_filename: "5.webp",
  image_path: "public/uploads/5.webp",
  university: "Princeton University",
  work: "Photographer",
  gym: "Planet Fitness",
  bucketlist: ["traveling to Iceland", "seeing the Northern Lights"],
},
{
  name: "Sophia King",
  email: "sophiaking@example.com",
  password: "Password1234$",
  age: 30,
  gender: "female",
  zip: "90003",
  bio: "I'm a food blogger and I love trying new recipes",
  preferences: ["food", "travel"],
  image_destination: "public/uploads/",
  image_filename: "8.jpg",
  image_path: "public/uploads/8.jpg",
  university: "University of Southern California",
  work: "Food Blogger",
  gym: "Anytime Fitness",
  bucketlist: ["traveling to Thailand", "learning to cook Thai food"],
},
{
  name: "Jacob Rodriguez",
  email: "jacobrodriguez@example.com",
  password: "Password1234$",
  age: 27,
  gender: "male",
  zip: "10005",
  bio: "I'm a gamer and I love playing video games",
  preferences: ["video games", "travel"],
  image_destination: "public/uploads/",
  image_filename: "9.jpg",
  image_path: "public/uploads/9.jpg",
  university: "University of California, Berkeley",
  work: "Software Developer",
  gym: "Anytime Fitness",
  bucketlist: ["traveling to Japan", "attending Tokyo Game Show"],
},
{
  name: "Isabella Green",
  email: "isabellagreen@example.com",
  password: "Password1234$",
  age: 29,
  gender: "female",
  zip: "10006",
  bio: "I love painting and going to art galleries",
  preferences: ["art", "travel"],
  image_destination: "public/uploads/",
  image_filename: "10.jpg",
  image_path: "public/uploads/10.jpg",
  university: "University of California, San Diego",
  work: "Artist",
  gym: "Equinox",
  bucketlist: ["traveling to France", "visiting the Louvre Museum"],
},{    name: "Sophia Martinez",    email: "sophiamartinez@example.com",    password: "Password1234$",    age: 30,    gender: "female",    zip: "10005",    bio: "I'm a nature lover and I love hiking",    preferences: ["hiking", "travel"],
image_destination: "public/uploads/",
image_filename: "6.jpg",
image_path: "public/uploads/6.jpg",
university: "Princeton University",
work: "Environmental Scientist",
gym: "LA Fitness",
bucketlist: ["hiking the Grand Canyon", "traveling to New Zealand"],
},
{
name: "Daniel Kim",
email: "danielkim@example.com",
password: "Password1234$",
age: 28,
gender: "male",
zip: "20003",
bio: "I'm a coffee addict and I love trying new cafes",
preferences: ["coffee", "travel"],
image_destination: "public/uploads/",
image_filename: "7.jpg",
image_path: "public/uploads/7.jpg",
university: "University of Pennsylvania",
work: "Software Developer",
gym: "Equinox",
bucketlist: ["skydiving", "traveling to South Korea"],
},
{
name: "Isabella Rodriguez",
email: "isabellarodriguez@example.com",
password: "Password1234$",
age: 27,
gender: "female",
zip: "90002",
bio: "I'm a fashion enthusiast and I love shopping",
preferences: ["fashion", "travel"],
image_destination: "public/uploads/",
image_filename: "8.jpg",
image_path: "public/uploads/8.jpg",
university: "New York University",
work: "Fashion Designer",
gym: "Barry's Bootcamp",
bucketlist: ["skydiving", "traveling to Paris"],
},
{
name: "Elijah Lee",
email: "elijahlee@example.com",
password: "Password1234$",
age: 26,
gender: "male",
zip: "10006",
bio: "I love playing basketball and watching movies",
preferences: ["basketball", "movies"],
image_destination: "public/uploads/",
image_filename: "9.jpg",
image_path: "public/uploads/9.jpg",
university: "Duke University",
work: "Financial Analyst",
gym: "YMCA",
bucketlist: ["skydiving", "traveling to Japan"],
},
{
name: "Mia Thompson",
email: "miathompson@example.com",
password: "Password1234$",
age: 29,
gender: "female",
zip: "10007",
bio: "I'm a bookworm and I love reading",
preferences: ["reading", "travel"],
image_destination: "public/uploads/",
image_filename: "10.jpg",
image_path: "public/uploads/10.jpg",
university: "Cornell University",
work: "Librarian",
gym: "Planet Fitness",
bucketlist: ["skydiving", "traveling to Greece"],
}
];

async function main() {
  const db = await dbConnection();
  await db.dropDatabase();

  for (let user of u) {
    try {
      await users.create(
        user.name,
        user.email,
        user.password,
        user.age,
        user.gender,
        user.zip,
        user.bio,
        user.preferences,
        user.image_destination,
        user.image_filename,
        user.image_path,
        user.university,
        user.work,
        user.gym,
        user.bucketlist
      );
      console.log(`User ${user.name} created`);
    } catch (error) {
      console.error(`Error creating user ${user.name}: ${error.message}`);
    }
  }

    await closeConnection();
}


main();