// seed the database

import * as users from "../data/users.js";
import { dbConnection, closeConnection } from "../config/mongoConnection.js";

const u = [
  {
    name: "John Doe",
    email: "johndoe@example.com",
    password: "Password1234$",
    age: 25,
    gender: "male",
    zip: "10001",
    bio: "I love hiking and playing video games",
    preferences: ["hiking", "video games"],
    image_destination: "public/uploads/",
    image_filename: "1.jpg",
    image_path: "public/uploads/1.jpg",
    university: "Harvard University",
    work: "Software Engineer",
    gym: "Gold's Gym",
    bucketlist: ["skydiving", "traveling to Japan"],
  },
  {
    name: "Jane Smith",
    email: "janesmith@example.com",
    password: "Password1234$",
    age: 28,
    gender: "female",
    zip: "20002",
    bio: "I'm a foodie and I love trying new restaurants",
    preferences: ["food", "travel"],
    image_destination: "public/uploads/",
    image_filename: "2.jpg",
    image_path: "public/uploads/2.jpg",
    university: "Yale University",
    work: "Marketing Manager",
    gym: "SoulCycle",
    bucketlist: ["skydiving", "traveling to Europe"],
  },
  {
    name: "Mike Johnson",
    email: "mikejohnson@example.com",
    password: "Password1234$",
    age: 30,
    gender: "male",
    zip: "90001",
    bio: "I'm a musician and I love playing guitar",
    preferences: ["music", "travel"],
    image_destination: "public/uploads/",
    image_filename: "3.jpg",
    image_path: "public/uploads/3.jpg",
    university: "University of California, Los Angeles",
    work: "Musician",
    gym: "Equinox",
    bucketlist: ["skydiving", "traveling to Australia"],
  },
  {
    name: "Sarah Davis",
    email: "sarahdavis@example.com",
    password: "Password1234$",
    age: 26,
    gender: "female",
    zip: "10002",
    bio: "I love reading and going on hikes",
    preferences: ["reading", "hiking"],
    image_destination: "public/uploads/",
    image_filename: "4.jpg",
    image_path: "public/uploads/4.jpg",
    university: "Stanford University",
    work: "Journalist",
    gym: "24 Hour Fitness",
    bucketlist: ["skydiving", "traveling to Italy"],
  },
  {
    name: "David Jones",
    email: "davidjones@example.com",
    password: "Password1234$",
    age: 27,
    gender: "male",
    zip: "10003",
    bio: "I'm a fitness enthusiast and I love working out",
    preferences: ["fitness", "travel"],
    image_destination: "public/uploads/",
    image_filename: "5.webp",
    image_path: "public/uploads/5.webp",
    university: "Columbia University",
    work: "Personal Trainer",
    gym: "Crunch Fitness",
    bucketlist: ["running a marathon", "traveling to Africa"],
  },
  {
    name: "Emily Brown",
    email: "emilybrown@example.com",
    password: "Password1234$",
    age: 29,
    gender: "female",
    zip: "10004",
    bio: "I'm a fashion lover and I love trying new clothes",
    preferences: ["fashion", "travel"],
    image_destination: "public/uploads/",
    image_filename: "5.webp",
    image_path: "public/uploads/5.webp",
    university: "New York University",
    work: "Fashion Stylist",
    gym: "Pure Barre",
    bucketlist: ["opening my own fashion line", "traveling to Paris"],
  },
  // {
  //   name: "Peter Green",
  //   name: "petergreen@example.com",
  //   password: "Password1234$",
  //   age: 31,
  //   gender: "male",
  //   zip: "10005",
  //   bio: "I'm a techie and I love working on computers",
  //   preferences: ["tech", "travel"],
  //   image_destination: "public/uploads/",
  //   image_filename: "5.webp",
  //   image_path: "public/uploads/5.webp",
  //   university: "Stanford University",
  //   work: "Software Engineer",
  //   gym: "Googleplex Gym",
  //   bucketlist: ["building my own startup", "traveling to Silicon Valley"],
  // },
  {
    name: "Alice White",
    email: "alicewhite@example.com",
    password: "Password1234$",
    age: 24,
    gender: "female",
    zip: "10006",
    bio: "I'm a student and I love learning new things",
    preferences: ["learning", "travel"],
    image_destination: "public/uploads/",
    image_filename: "5.webp",
    image_path: "public/uploads/5.webp",
    university: "New York University",
    work: "Student",
    gym: "NYU Fitness Center",
    bucketlist: ["getting a PhD", "traveling to all 7 continents"],
  },
  {
    name: "Alexandra Miller",
    email: "alexandramiller@example.com",
    password: "Password1234$",
    age: 25,
    gender: "female",
    zip: "94102",
    bio: "I'm a writer and I love to read",
    preferences: ["writing", "reading"],
    image_destination: "public/uploads/",
    image_filename: "5.webp",
    image_path: "public/uploads/5.webp",
    university: "University of California, Berkeley",
    work: "Freelance Writer",
    gym: "Crunch Fitness",
    bucketlist: ["writing a novel", "traveling to all 50 states"],
  },
  {
    name: "Benjamin Smith",
    email: "benjaminsmith@example.com",
    password: "Password1234$",
    age: 28,
    gender: "male",
    zip: "94103",
    bio: "I'm a musician and I love to play the guitar",
    preferences: ["music", "playing guitar"],
    image_destination: "public/uploads/",
    image_filename: "5.webp",
    image_path: "public/uploads/5.webp",
    university: "San Francisco State University",
    work: "Musician",
    gym: "Equinox",
    bucketlist: ["playing in a band", "traveling to Europe"],
  },
  {
    name: "Caroline Jones",
    email: "carolinejones@example.com",
    password: "Password1234$",
    age: 30,
    gender: "female",
    zip: "94104",
    bio: "I'm a student and I love to learn new things",
    preferences: ["learning", "travel"],
    image_destination: "public/uploads/",
    image_filename: "5.webp",
    image_path: "public/uploads/5.webp",
    university: "University of California, San Francisco",
    work: "Student",
    gym: "24 Hour Fitness",
    bucketlist: ["getting a PhD", "traveling to all 7 continents"],
  },
  {
    name: "Daniel Thomas",
    email: "danielthomas@example.com",
    password: "Password1234$",
    age: 26,
    gender: "male",
    zip: "94105",
    bio: "I'm a fitness enthusiast and I love working out",
    preferences: ["fitness", "travel"],
    image_destination: "public/uploads/",
    image_filename: "5.webp",
    image_path: "public/uploads/5.webp",
    university: "Stanford University",
    work: "Personal Trainer",
    gym: "Crunch Fitness",
    bucketlist: ["running a marathon", "traveling to Africa"],
  },
];

async function main() {
  const db = await dbConnection();
  await db.dropDatabase();

  for (let user of u) {
    try {
      await users.create(
        user.name,
        user.email,
        user.password,
        user.age,
        user.gender,
        user.zip,
        user.bio,
        user.preferences,
        user.image_destination,
        user.image_filename,
        user.image_path,
        user.university,
        user.work,
        user.gym,
        user.bucketlist
      );
      console.log(`User ${user.name} created`);
    } catch (error) {
      console.error(`Error creating user ${user.name}: ${error.message}`);
    }
  }

    await closeConnection();
}


main();